version: "3"

services:

  configuration-sdk-java-preview-test:
    build: .
    container_name: configuration-sdk-java-preview-test
    image: maven:3.8.5-jdk-11
    environment:
      - FBN_TOKEN_URL
      - FBN_USERNAME
      - FBN_PASSWORD
      - FBN_CLIENT_ID
      - FBN_CLIENT_SECRET
      - FBN_APP_NAME
      - FBN_CONFIGURATION_API_URL=${FBN_BASE_API_URL}/configuration
      - FBN_ACCESS_TOKEN    
    volumes:
      - .:/usr/src